version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
    - .:/app
    - ./_build:/app/_build
    stdin_open: true
    tty: true
    ports:
      - 4000:4000
    expose:
      - 4000
    networks:
      default:
        aliases:
          - application
    depends_on:
      - db

  db:
    image: postgres:15.2-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - 'pgdata:/var/lib/postgresql/data'
    ports:
      - 5432:5432
    expose:
      - 5432
    networks:
      default:
        aliases:
          - postgres

volumes:
  pgdata:

networks:
  default:
        
